Repository SyneRBI/SIRF-SuperBuild, pull requests merged in 2024-03, with the labels that each got.

#884 [VB] add extra options for developers
  CHANGES.md
  VirtualBox/scripts/UPDATE_functions.sh
Labels: enhancement

#891 docker docs
  .github/workflows/docker.yml
  docker-compose.yml
  docker/README.md
  docker/compose.sh
  docker/devel/shared.txt
  docker/docker-compose.devel-gpu.yml
  docker/docker-compose.devel.yml
  docker/docker-compose.gpu.yml
Labels: bug, enhancement

#839 revert to `conda` but with `libmamba` solver
  CHANGES.md
  docker/install-sirf-exercises-dep.py
  docker/user_demos.sh
  docker/user_python-ubuntu.sh
Labels: in-review
