Repository SyneRBI/SIRF-SuperBuild, pull requests merged in 2024-06, with the labels that each got.

#906 update parallelproj to 1.9.0 (and require it), as well as CIL, SIRF, STIR
  CHANGES.md
  docker/requirements.yml
  version_config.cmake
Labels: bug, enhancement, upstream_problem

#913 bump CIL
  CHANGES.md
  version_config.cmake
Labels: bug, enhancement, in-review

#914 bump CIL
  CHANGES.md
  version_config.cmake
Labels: bug
